import { toActionsTypes } from 'cfx.redux-types'

export default toActionsTypes {

  # LOGIN REDUCE
  'LOGIN_SAVE'
  'LOGIN_SIGNOUT'

  # LOGIN SAGAS
  'LOGIN_SIGNUP'
  'LOGIN_LOGIN'
  
  # USER REDUCE
  'USER_SAVE'
  'USER_PATCH'
  'USER_REMOVE'
  'USER_SAVE_ALL'
  'USER_REMOVE_ALL'

  # USER SAGAS
  'USER_CREATE'
  'USER_FETCH'
  'USER_RELOAD'
  'USER_UPDATE'
  'USER_DELETE'
  'USER_VER_EMAIL'
  'USER_RESET_PSD'
  'USER_REFRESH_TOKEN'
  'USER_RESET_SESSIONTOKEN' 
  'USER_RESET_PSD_WITH_EMAIL'
  
  # LANDLORD REDUCE
  'LANDLORD_SAVE'
  'LANDLORD_PATCH'
  'LANDLORD_REMOVE'
  'LANDLORD_SAVE_ALL'  
  'LANDLORD_REMOVE_ALL'

  # LANDLORD SAGAS
  'LANDLORD_CREATE'
  'LANDLORD_FETCH'
  'LANDLORD_RELOAD'
  'LANDLORD_UPDATE'
  'LANDLORD_DELETE'

  # TENANT REDUCE
  'TENANT_SAVE'
  'TENANT_PATCH'
  'TENANT_REMOVE'  
  'TENANT_SAVE_ALL'
  'TENANT_REMOVE_ALL'

  # TENANT SAGAS
  'TENANT_CREATE'
  'TENANT_FETCH'
  'TENANT_RELOAD'
  'TENANT_UPDATE'
  'TENANT_DELETE'

  # TODO REDUCE
  'TODO_SAVE'
  'TODO_PATCH'
  'TODO_REMOVE'
  'TODO_SAVE_ALL'
  'TODO_REMOVE_ALL'

  # TODO SAGAS
  'TODO_CREATE'
  'TODO_FETCH'
  'TODO_RELOAD'
  'TODO_UPDATE'
  'TODO_DELETE'  

  # NOTICE REDUCE
  'NOTICE_SAVE'
  'NOTICE_PATCH'
  'NOTICE_REMOVE'
  'NOTICE_SAVE_ALL'  
  'NOTICE_REMOVE_ALL'

  # NOTICE SAGAS
  'NOTICE_CREATE'
  'NOTICE_FETCH'
  'NOTICE_RELOAD'
  'NOTICE_UPDATE'
  'NOTICE_DELETE'
  
  # HOUSE REDUCE
  'HOUSE_SAVE'
  'HOUSE_SAVE_ALL'
  'HOUSE_REMOVE'
  'HOUSE_REMOVE_ALL'
  'HOUSE_PATCH'

  # HOUSE sagas
  'HOUSE_CREATE'
  'HOUSE_DELETE'
  'HOUSE_UPDATE'
  'HOUSE_FETCH'
  'HOUSE_RELOAD'

  # ROOM REDUCE
  'ROOM_SAVE'
  'ROOM_SAVE_ALL'
  'ROOM_REMOVE'
  'ROOM_REMOVE_ALL'
  'ROOM_PATCH'

  # ROOM sagas
  'ROOM_CREATE'
  'ROOM_DELETE'
  'ROOM_UPDATE'
  'ROOM_FETCH'
  'ROOM_RELOAD'

  # BED REDUCE
  'BED_SAVE'
  'BED_SAVE_ALL'
  'BED_REMOVE'
  'BED_REMOVE_ALL'
  'BED_PATCH'

  # BED sagas
  'BED_CREATE'
  'BED_DELETE'
  'BED_UPDATE'
  'BED_FETCH'
  'BED_RELOAD'

  # RENT REDUCE
  'RENT_SAVE'
  'RENT_SAVE_ALL'
  'RENT_REMOVE'
  'RENT_REMOVE_ALL'
  'RENT_PATCH'
  
  # RENT sagas
  'RENT_CREATE'
  'RENT_DELETE'
  'RENT_UPDATE'
  'RENT_FETCH'
  'RENT_RELOAD'
}
