# import bed from './reducers/bed'
# import todo from './reducers/todo'
# import user from './reducers/user'
# import rent from './reducers/rent'
# import room from './reducers/room'
# import house from './reducers/house'
# import login from './reducers/login'
# import notice from './reducers/notice'
# import tenant from './reducers/tenant'
# import landlord from './reducers/landlord'

# export default {
#   bed...
#   todo...
#   user...
#   rent...
#   room...
#   house...
#   login...     
#   notice...
#   tenant...
#   landlord...
# }
  