# import bed from './sagas/bed'
# import user from './sagas/user'
# import rent from './sagas/rent'
# import room from './sagas/room'
# import todo from './sagas/todo'
# import login from './sagas/login'
# import house from './sagas/house'
# import notice from './sagas/notice'
# import tenant from './sagas/tenant'
# import landlord from './sagas/landlord'

# export default {
#   bed...
#   user...
#   rent...
#   room...
#   todo...
#   login...
#   house...
#   notice...
#   tenant...
#   landlord...
# }
